# Create the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copy the published output from local publish directory
COPY ./publish .

# Set the listening address to all IPs to be accessible within Kubernetes
ENV ASPNETCORE_URLS=http://+:80

EXPOSE 80
ENTRYPOINT ["dotnet", "mvc.dll"]
