apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activemq
  namespace: dotnet-test
spec:
  serviceName: "activemq-headless"
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      # 以 root 身份运行（保证有写权限）
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: activemq
        image: rmohr/activemq:5.15.9
        imagePullPolicy: IfNotPresent
        env:
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: "admin"
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: "admin"
        ports:
        - name: openwire
          containerPort: 61616   # ActiveMQ 消息端口
        - name: web
          containerPort: 8161    # Web 控制台端口
        volumeMounts:
        - name: activemq-tmp
          mountPath: /opt/activemq/tmp
        - name: activemq-data
          mountPath: /opt/activemq/data
      volumes:
      - name: activemq-tmp
        emptyDir: {}
      - name: activemq-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-headless
  namespace: dotnet-test
spec:
  clusterIP: None
  selector:
    app: activemq
  ports:
    - name: openwire
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  namespace: dotnet-test
spec:
  selector:
    app: activemq
  ports:
    - name: openwire
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
  type: ClusterIP
