apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activemq
  namespace: dotnet-test
spec:
  serviceName: "activemq-headless"
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: rmohr/activemq:5.16.5
        imagePullPolicy: IfNotPresent
        env:
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: "admin"
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: "admin"
        ports:
        - name: openwire
          containerPort: 61616   # ActiveMQ 消息端口
        - name: web
          containerPort: 8161    # Web 控制台端口
        volumeMounts:
        - name: middleware-storage
          mountPath: /opt/activemq/data
          subPath: activemq
      volumes:
      - name: middleware-storage
        persistentVolumeClaim:
          claimName: middleware-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-headless
  namespace: dotnet-test
spec:
  clusterIP: None
  selector:
    app: activemq
  ports:
    - name: openwire
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  namespace: dotnet-test
spec:
  selector:
    app: activemq
  ports:
    - name: openwire
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
  type: ClusterIP
