apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-razor-pages
  namespace: dotnet-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-razor-pages
  template:
    metadata:
      labels:
        app: dotnet-razor-pages
    spec:
      containers:
      - name: dotnet-razor-pages
        image: docker.io/library/dotnet-razor-pages:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-razor-pages-service
  namespace: dotnet-test
spec:
  selector:
    app: dotnet-razor-pages
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnet-razor-pages-ingress
  namespace: dotnet-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: razor.ziyou.com
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: dotnet-razor-pages-service
            port:
              number: 80