apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: dotnet-test
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/library/redis:6-alpine
        imagePullPolicy: IfNotPresent
        command: ["redis-server", "--requirepass", "Middleware123"]
        env:
        - name: REDIS_PASSWORD
          value: "Middleware123"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: middleware-storage
          mountPath: /data
          subPath: redis
      volumes:
      - name: middleware-storage
        persistentVolumeClaim:
          claimName: middleware-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: dotnet-test
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: dotnet-test
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP